{% set name = "fenicsx-beat" %}
{% set python_min = "3.12" %}
{% set version = "0.7.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/finsberg/fenicsx-beat/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 95f8a8743a569ab2854c5b0d72d38f464ef9a4a5be3f7cc6baa06eac4e1e2c6a
  patches: 0001-Skip-postprocessing-tests.patch

build:
  number: 0
  noarch: python
  entry_points:
    - "beat=beat.cli:main"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scifem >=0.3.1
    - pint
    - rich
    - toml
    - pydantic
    - pydantic-pint
    - io4dolfinx
    - cardiac-geometriesx
    - gotranx
    - fenics-dolfinx
  

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pip
  imports:
    - beat
  source_files:
    - tests/
    - pyproject.toml
  commands:
    - pip check
    - beat --help
    - pytest --log-cli-level=debug -vvs --maxfail 4 -m "not postprocess" tests


about:
  home: https://github.com/finsberg/fenicsx-beat
  summary: Library to run cardiac EP simulation
  license: MIT
  license_file: LICENSE
  doc_url: https://finsberg.github.io/fenicsx-beat/
  dev_url: https://github.com/finsberg/fenicsx-beat

extra:
  recipe-maintainers:
    - finsberg
