{% set name = "fenicsx-beat" %}
{% set python_min = "3.10" %}
{% set version = "0.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fenicsx_beat-{{ version }}.tar.gz
  sha256: 3ed5085ef26c696b967824c550112ce4d930ff2e5cd4e3f02e7816aea3686ddc

build:
  number: 0
  noarch: python
  entry_points:
    - "beat=beat.cli:main"
  script: python -m pip install -v --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scifem >=0.3.1
    - pint
    - rich
    - fenics-dolfinx

test:
  requires:
    - python {{ python_min }}
    - pytest
    - pytest-cov
    - pip
  imports:
    - beat
  source_files:
    - tests/
    - pyproject.toml
  commands:
    - pip check
    - beat --help
    - pytest --log-cli-level=debug -vvs --maxfail 4 tests


about:
  home: https://github.com/finsberg/fenicsx-beat
  summary: Library to run cardiac EP simulation
  license: MIT
  license_file: LICENSE
  doc_url: https://finsberg.github.io/fenicsx-beat/
  dev_url: https://github.com/finsberg/fenicsx-beat

extra:
  recipe-maintainers:
    - finsberg
